#!/bin/bash

source="$1"
name=$(basename "$source")
object="$name.o"
binary="$name.exe"

function _clean_up {
    rm "$object" "$binary"
}

set -e
trap _clean_up EXIT

nasm -f elf64 -o "$object" "$source"
gcc -o "$binary" "$object"
./"$binary"

